# Generated by Django 5.0.2 on 2026-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_type', models.CharField(max_length=20)),
                ('completed_steps', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'routine_logs',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedRemedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_remedies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkincareRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('routine_type', models.CharField(choices=[('morning', 'Morning'), ('night', 'Night'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skincare_routines',
                'ordering': ['routine_type', '-created_at'],
            },
        ),
    ]
