# Generated by Django 5.0.2 on 2026-04-06 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='products.product'),
        ),
        migrations.AddField(
            model_name='savedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedremedy',
            name='remedy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='products.naturalremedy'),
        ),
        migrations.AddField(
            model_name='savedremedy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_remedies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skincareroutine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='recommendations.skincareroutine'),
        ),
        migrations.AlterUniqueTogether(
            name='savedproduct',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='savedremedy',
            unique_together={('user', 'remedy')},
        ),
    ]
