# Generated by Django 5.0.2 on 2026-05-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Skincare Routine', max_length=200)),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routines',
                'ordering': ['time_of_day', 'created_at'],
                'unique_together': {('user', 'time_of_day')},
            },
        ),
        migrations.CreateModel(
            name='RoutineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('days_of_week', models.JSONField(default=list, help_text='[0,1,2,3,4,5,6] where 0=Monday')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routine_reminders',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('eye_cream', 'Eye Cream'), ('treatment', 'Treatment'), ('exfoliator', 'Exfoliator'), ('mask', 'Mask'), ('other', 'Other')], max_length=20)),
                ('product_name', models.CharField(blank=True, help_text='Manual product name if no product linked', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='How long to apply (e.g., 60s)', null=True)),
                ('is_weather_dependent', models.BooleanField(default=False, help_text='Adjust based on weather conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_steps', to='products.product')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='routines.routine')),
            ],
            options={
                'db_table': 'routine_steps',
                'ordering': ['routine', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(choices=[('hot_humid', 'Hot & Humid'), ('hot_dry', 'Hot & Dry'), ('cold_humid', 'Cold & Humid'), ('cold_dry', 'Cold & Dry'), ('polluted', 'High Pollution'), ('sunny', 'Sunny/High UV'), ('rainy', 'Rainy'), ('normal', 'Normal/Mild')], max_length=20)),
                ('adjustment_notes', models.TextField(blank=True)),
                ('add_steps', models.JSONField(default=list, help_text='Step types to add in this weather')),
                ('remove_steps', models.JSONField(default=list, help_text='Step types to skip in this weather')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_adaptations', to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_adaptations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weather_adaptations',
                'unique_together': {('user', 'weather_condition')},
            },
        ),
    ]
