# Generated by Django 5.0.2 on 2026-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('scan_count', 'Scan Count'), ('streak', 'Routine Streak'), ('score', 'Skin Score'), ('improvement', 'Improvement')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value', models.IntegerField(default=0)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress_photos/')),
                ('skin_score', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'progress_photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
