# Generated by Django 5.0.2 on 2026-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('routine', 'Skincare Routine'), ('product', 'Product Recommendation'), ('concern', 'Skin Concern'), ('ingredient', 'Ingredients'), ('general', 'General')], default='general', max_length=20)),
                ('answer_text', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=dict)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('processing_time', models.FloatField(default=0.0)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkinScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skin_scans/')),
                ('scan_type', models.CharField(choices=[('full_face', 'Full Face Scan'), ('spot', 'Spot Analysis'), ('forehead', 'Forehead'), ('cheeks', 'Cheeks'), ('chin', 'Chin'), ('nose', 'Nose')], default='full_face', max_length=20)),
                ('detected_issues', models.JSONField(default=list)),
                ('severity', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('skin_score', models.IntegerField(default=0)),
                ('analysis_text', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=dict)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skin Scan',
                'verbose_name_plural': 'Skin Scans',
                'db_table': 'skin_scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
