# Generated by Django 5.0.2 on 2026-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinscan',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
    ]
