# Generated by Django 5.0.2 on 2026-05-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Product barcode (EAN/UPC)', max_length=50, null=True, unique=True),
        ),
    ]
